Update CI and add OCI labels

diff --git a/.github/workflows/docker-image-ci.yaml b/.github/workflows/docker-image-ci.yaml
--- a/.github/workflows/docker-image-ci.yaml
+++ b/.github/workflows/docker-image-ci.yaml
@@ -13,13 +13,23 @@ jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
+      - name: Check tag
+        if: github.ref_type == 'tag'
+        run: |
+          if [[ ! $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid tag format. Expected: vX.Y (e.g., v1.0)" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
       - name: Set variables
         id: vars
         run: |
           echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
+          echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
           ghcr_ref="ghcr.io/${{ github.repository_owner }}/nordlynx"
-          dockerhub_ref="${{ github.repository_owner }}/nordlynx"
+          dockerhub_ref="${{ vars.DOCKERHUB_NAMESPACE }}/nordlynx"
           if [[ $GITHUB_REF_TYPE == tag ]]; then
+            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
             echo "ghcr_tags=${ghcr_ref}:${GITHUB_REF_NAME},${ghcr_ref}:latest" >> $GITHUB_OUTPUT
             echo "dockerhub_tags=${dockerhub_ref}:${GITHUB_REF_NAME},${dockerhub_ref}:latest" >> $GITHUB_OUTPUT
           else
@@ -46,7 +56,7 @@ jobs:
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: jhauseux
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Build and push
@@ -58,3 +68,6 @@ jobs:
           platforms: linux/amd64,linux/arm64
           build-args: |
             BUILD_DATE=${{ steps.vars.outputs.date }}
+            REPO_URL=${{ github.server_url }}/${{ github.repository }}
+            VCS_REF=${{ steps.vars.outputs.sha_short }}
+            VERSION=${{ github.ref_name }}
